### ISSUE TITLE
`clearRequireCache` does not clear `require`

### ISSUE THREAD

**Issue by dmtrs** [pghalliday/grunt-mocha-test#101]
I am using `grunt-mocha-test` along with `grunt-contrib-watch` and watch has `spawn: false`. The `mochaTest` part looks as follows:
```js
        mochaTest: {
            test: {
                options: {
                    reporter: 'list',
                    quiet: false,
                    clearRequireCache: true,
                    require: [ 'babel/register' ],
                    colors: false
                },
                src: ['src/**/*.test.js']
            }
        },
```

You can notice the `require` has value `babel/register` which is the compiler I want to use, but unfortunately in the second run from a watch trigger I get:
```
Running "mochaTest:test" (mochaTest) task
Warning: only one instance of babel/polyfill is allowed
```

so I suppose the `clearRequireCache` does not affect the requires from `require`param.

**Comment by pghalliday** [comment]
I will have to run some tests.

**Comment by pghalliday** [comment]
I don't know what the babel register module does, but i just ran a test and if i require a simple module with the require option that sets a global variable and if I change that variable and then clear the require cache the next test run gets the original value of the global as I would expect. If i repeat the test without the clearRequireCache option then the next test run starts with the modified value of the global, also as I would expect.

Maybe you could investigate what Babel does that's different - i'm afraid i likely won't have the time

**Comment by pghalliday** [comment]
I think i know why you get your error and it has nothing to do with clearing the require cache. Babel's register method has this code:

```
if (global._babelPolyfill) {
  throw new Error("only one instance of babel/polyfill is allowed");
}
global._babelPolyfill = true;
```

Clearing the require cache does not reset global variables it just unloads the modules so that if they are required again they are loaded and run again. In this case you can avoid the error by not clearing the require cache (in which case the babel register module will not be rerun).

It may be that you need to clear the require cache for other reasons, in which case I suggest that you use watch with the spawn option enabled instead.

I did have a plan to add an exclude list to the `clearRequireCache` option, but this is far from imminent

**Comment by pghalliday** [comment]
Correction if you don't clear the require cache then your tests will not rerun, so that's not really an option. You may try wrapping the register require in another module that checks if it's already loaded. eg.

```
// myRequire.js
if (!global._myRequire) {
  require('babel/register');
}
global._myRequire = true;
```

I don't know if this will work in your use case or not.

**Comment by dmtrs** [comment]
Thanks for the response @pghalliday 

I will try your recommendation of find another work around.

**Comment by proehlen** [comment]
Has anyone found a solution for this?  I have the exact same issue as outlined in the above issue.
