### ISSUE TITLE
Mocha-test options for good-mocha-html-reporter

### ISSUE THREAD

**Issue by DeChrish** [pghalliday/grunt-mocha-test#103]
Mocha options :
config.mochaTest[name] = {
options: {
reporter: 'good-mocha-html-reporter',
timeout: 60000,
logErrors: true,
captureFile: directories.target + '/' + name + '/test-results.html'
}

good-mocha-html-reporter - config file:
module.exports = {
path: '', // full or relative path (relative to your execution folder)
filename: 'report.html',
mode: 'Verbose'
}

When i use 'good-mocha-html-reporter' in mocha options, the report is generated as 'report.html' which is added in reporter-config file.
I want to use captureFile option to save the report file.
Is it possible?

**Comment by pghalliday** [comment]
I had a quick look at the source for `good-mocha-html-reporter` and as far as I can tell it always uses `fs.writeFileSync` and a file path to generate the report file. The `captureFile` option just captures the console output (`stdout`). I noticed that the `good-mocha-html-reporter` also writes other output to the console.

So the short answer is no this won't work.

The long answer is that you might be able to hack things so that the console output from `good-mocha-html-reporter` went somewhere else and create some kind of file descriptor that actually redirected to `stdout` or maybe simpler, hack with `fs.writeFileSync` in that context to make it write to `stdout`. It doesn't seem worth it though.

You may want to raise an issue over at https://github.com/Gauge/html_table_reporter to add an option to write the html to `stdout` (and silence other output). On that note you could fork it and add the options yourself ;)

Also bear in mind that `captureFile` is a last resort option and actually, I would say that if your reporter offers a file output option then it would be better to use it. The reason is again that `captureFile` is agnostic and so captures everything on `stdout`, including any console output from your tests. Normally I keep my tests clean so they don't output to console, but for some folks this can be a painful limitation

**Comment by pghalliday** [comment]
As an after thought, if your goal is to keep your configuration in one place (the `gruntfile`) then you could add a task that writes the `good-mocha-html-reporter` config file out when you run grunt and then `.gitignore` it

**Comment by pghalliday** [comment]
Ooh, nasty. I just had a closer look and it seems the `good-mocha-html-reporter` config file is actually inside the module source in `node_modules` - I think this is an awful pattern (IMHO) as in most cases this would not be checked into to source code control. I would recommend raising an issue against it. However it makes the option of getting grunt to generate this config before running the tests much more attractive (if not essential)

**Comment by Gauge** [comment]
@pghalliday I am implementing the changes you suggested. As for the config file, i am aware of how nasty it is. I was running short on time when i initially created it.

**Comment by DeChrish** [comment]
@pghalliday thanks for all your comments, i have raised the issue html_table_reporter repo. Let me get check the latest version.
https://github.com/Gauge/html_table_reporter/issues/1

**Comment by pghalliday** [comment]
Cool, I think i'll close this. Thanks :)
