### ISSUE TITLE
Stacktrace when mocha throws a warning

### ISSUE THREAD

**Issue by pedrommuller** [pghalliday/grunt-mocha-test#113]
Hi,

I'd like to see the stacktrace when I get a warning from a mocha test, my tests are failing with a warning and the only message received is this:

> Warning: Cannot redefine property: router Used --force, continuing.

I'm running mocha with grunt and also using --stack and it doesn't make any difference

I don't mind to treat warning as errors, but I haven't found how o configure it neither.

debugging in this situation is very difficult, so any advice will be more than welcome.

**Comment by pghalliday** [comment]
Can you provide an example project to demonstrate this?

**Comment by machineghost** [comment]
Any time any error happens outside of a callback passed to Mocha the stack trace is lost.  Here's a simple example:

    //throw ('a');
    describe('Foo', () => {
        //throw new Error('b');
        beforeEach(() => {
            //throw new Error('c');
        });
        it('does bar', () => {
            throw new Error('d');
        });
    });

If you un-comment the earlier errors (one at a time of course) you'll see that "c" and "d" tell you where the error occurred.  However "a" and "b" display literally just that ("a" or "b"); no stack trace.

This is *really* annoying, because whenever one of these errors happens I have to resort "delete debugging" (delete random chunks of code until the error goes away, thereby telling me where it is).

Please tell me there's some way for Mocha to throw in a `try`/`catch` at the top somewhere and show the stack traces on these errors; it will save me (and probably lots of others) a ton of time.

**Comment by pghalliday** [comment]
@machineghost is that the same issue? Anyway I just reproduced this and I hate to say it but your understanding of `throw` is incorrect. It does not add a stack trace so the existing try/catch for this doesn't help. The stack trace is added when you create a new `Error`. If you change your code to this you will see the stack trace:

```
throw new Error('a');
describe('Foo', () => {
    //throw new Error('b');
    beforeEach(() => {
        //throw new Error('c');
    });
    it('does bar', () => {
        throw new Error('d');
    });
});
```

**Comment by machineghost** [comment]
My apologies, I was confused.  There is a real issue with Mocha not providing stacktraces in the cases I mentioned if you use AMD ... but that has nothing to do with grunt-mocha-test.

**Comment by pghalliday** [comment]
ah, ok thanks
