### ISSUE TITLE
Freezes on mocha 6

### ISSUE THREAD

**Issue by senseysensor** [pghalliday/grunt-mocha-test#137]
All tests pass normally but seems mocha just doesn't exit - and grunt hangs. Before on mocha 5 everything was ok.

node version – v10.15.1
mocha version – 6.0.1

**Comment by Kampfmoehre** [comment]
I'm just getting `Warning: Cannot read property 'toString' of undefined Use --force to continue.
` and no tests run at all. 
After investigating the problem further, I found, that mocha had a problem in the timeout function where it tries to set the timeout. However I had no timeout defined, thus it was getting undefined. I work around this, by specifying a timeout option in my grunt config like `timeout: false`.

This is where mocha checks the options and tries to configure the timeout: https://github.com/mochajs/mocha/blob/v6.0.2/lib/mocha.js#L124. Because neither options where set it passes undefined to the timeout function.

This is where the error comes from:
https://github.com/mochajs/mocha/blob/v6.0.2/lib/suite.js#L124.

Not sure if this is more a mocha problem, but running mocha directly worked for me. Maybe you should set timeout to false if it is not specified by the user.

**Comment by senseysensor** [comment]
Sorry, after further investigation real source of the issue was mocha-multi reporter (after its disabling things got worked). I will open ticket there.
